### ISSUE TITLE
CFME Archive log collection is now broken

### ISSUE THREAD

**Issue by thennessy** [redhat-cfme-support/cloudforms_4.X_log_collection#1]
redhat-cfme-support cloudforms_4.x_log_collection no compromised.  the archive log collection no longer collects archive logs.

**Comment by jdeubel** [comment]
commit 780830adf93d7dc6b76a67a5e81ec4e3104e5b64
Merge: 6da2ce0 30089a9
Author: Jared Deubel jdeubel@redhat.com
Date:   Tue Nov 1 13:08:41 2016 -0400

```
Merge branch 'log_collection_archive_fix'
```

commit 30089a91a6e0958a397bbfac1b6e1e31870a4d66
Author: Jared Deubel jdeubel@redhat.com
Date:   Tue Nov 1 13:02:22 2016 -0400

```
Added tar.xz to else statement as only current logs where being collected
```

**Comment by jdeubel** [comment]
@thennessy  Please let me know if you have any issues.

**Comment by jcarter12** [comment]
Thanks for correcting the issue @jdeubel
